---
- hosts: all
  gather_facts: no
  tasks:
    - name: Retrieve the committed configuration
      junos_config:
        backup: yes
        backup_options:
          dir_path: '../config_backups'
          filename: base-config.backup
    #   register: response
    # - name: Print the lines in the config.
    #   debug:
    #     var: response.config_lines








