---
- hosts: all
  vars:
    ansible_command_timeout: 120
  gather_facts: no
  tasks:
    - name: Allow all traffic within CUSTOMER_PUBLIC zone 
      junos_config:
        lines:
          - set system syslog user * any emergency
          - set system syslog host 10.87.129.16 any any
          - set system syslog host 10.87.129.16 match RT_FLOW_SESSION
          - set system syslog file messages any any
          - set system syslog file messages authorization info
          - set system syslog file interactive-commands interactive-commands any
          - set security log mode stream
          - set security log source-address 172.168.0.3
          - set security log stream S1 format syslog
          - set security log stream S1 category all
          - set security log stream S1 host 10.87.129.16