---
- hosts: all
  vars_files:
     - ../playbook_vars/deployment_vars.yml
  gather_facts: no
  tasks:
    - name: Add VPC-NETWORK and subnet to the vSRX global address book 
      junos_config:
        lines:
          - set security address-book global address VPC-NETWORK 10.240.0.0/24
    - name: Set up tunnel interfaces and security zone 
      junos_config:
        lines:
          - set interfaces st0 unit 1 family inet address 169.254.200.0/31
          - set security zones security-zone VPN interfaces st0.1 host-inbound-traffic system-services all
    - name: Set up ike policy and interface  
      junos_config:

    - name: Set up ipsec policies and proposal  
      junos_config:
        lines: 
          - set security ipsec traceoptions flag all
          - set security ipsec proposal ipsec-prop protocol esp
          - set security ipsec proposal ipsec-prop authentication-algorithm hmac-sha-256-128 
          - set security ipsec proposal ipsec-prop encryption-algorithm aes-256-cbc 
          - set security ipsec policy ipsec-pol proposals ipsec-prop
          - set security ipsec vpn ipsec-vpn1 vpn-monitor
          - set security ipsec vpn ipsec-vpn1 ike ipsec-policy ipsec-pol 
          - set security ipsec vpn ipsec-vpn1 bind-interface st0.1
          - set security ipsec vpn ipsec-vpn1 ike ipsec-policy ipsec-pol  
          - set security ipsec vpn ipsec-vpn1 ike gateway gw-vpc
          - set security ipsec vpn ipsec-vpn1 establish-tunnels immediately
    - name: Set up CUSTOMER-PRIVATE to VPN zone security policies 
      junos_config:
        lines:
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN description "Allow all traffic from CUSTOMER-PRIVATE to VPN zone"
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN match source-address VSI-PRI-NET    
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN match destination-address VPC-NETWORK
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN match application any
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN then permit
    - name: Set up VPN to CUSTOMER-PRIVATE zone security policies 
      junos_config:
        lines:
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN description "Allow all traffic from CUSTOMER-PRIVATE to VPN zone"
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN match source-address VPC-NETWORK    
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN match destination-address VSI-PRI-NET
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN match application any
          - set security policies from-zone CUSTOMER-PRIVATE to-zone VPN policy Custprivate-to-VPN then permit
