---
- hosts: all
  vars:
    ansible_command_timeout: 120
    syslog_server_ip: "SYSLOG_IP"
  gather_facts: no
  tasks:
    - name: Add a syslog server to vSRX system 
      junos_config:
        lines:
          - set system syslog user * any emergency
          - set system syslog host "{{ syslog_server_ip }}" any any
          - set system syslog host "{{ syslog_server_ip }}" match RT_FLOW_SESSION
          - set system syslog file messages any any
          - set system syslog file messages authorization info
          - set system syslog file interactive-commands interactive-commands any
          - set security log mode stream
          - set security log source-address "{{ vsrx_private_ip }}"
          - set security log stream S1 format syslog
          - set security log stream S1 category all
          - set security log stream S1 host "{{ syslog_server_ip }}"