---
- hosts: all
  vars_files:
     - ../playbook_vars/deployment_vars.yml
  gather_facts: no
  tasks:
    - name: Add VPC-NETWORK and subnet to the vSRX global address book 
      junos_config:
        lines:
          - set security address-book global address VPC-NETWORK "{{ vpc_cidr }}"
    - name: Create interface for tunnel  
      junos_config:
        lines:
          - set interfaces st0 unit 0 description "VPN interface for vSRX"
          - set interfaces st0 unit 0 family inet
    - name: Set vpn routing  
      junos_config:
        lines:
          - set routing-options static route "{{ vpc_cidr }}" next-hop st0.0
    - name: Set security flow  
      junos_config:
        lines:
          - set security flow tcp-mss ipsec-vpn mss 1200
    - name: Set ike proposal 
      junos_config:
        lines:
          - set security ike proposal ike-proposal authentication-method pre-shared-keys
          - set security ike proposal ike-proposal dh-group group5
          - set security ike proposal ike-proposal authentication-algorithm sha1 
          - set security ike proposal ike-proposal encryption-algorithm aes-128-cbc
          - set security ike proposal ike-proposal lifetime-seconds 28800
    - name: Set ike policy 
      junos_config:
        lines:
          - set security ike policy ike-phase1-policy mode main
          - set security ike policy ike-phase1-policy proposals ike-proposal
          - set security ike policy ike-phase1-policy pre-shared-key ascii-text "{{ pre_shared_key }}"
    - name: Set ike gateway 
      junos_config:
        lines:
          - set security ike gateway vpnaas ike-policy ike-phase1-policy
          - set security ike gateway vpnaas address "{{ vpnaas_gateway }}"
          - set security ike gateway vpnaas dead-peer-detection interval 10
          - set security ike gateway vpnaas dead-peer-detection threshold 5
          - set security ike gateway vpnaas local-identity inet "{{ vsrx_public_ip }}"
          - set security ike gateway vpnaas external-interface ae1.0
          - set security ike gateway vpnaas general-ikeid
          - set security ike gateway vpnaas version v2-only
    - name: Set ipsec proposal 
      junos_config:
        lines:
          - set security ipsec proposal ipsec-phase2-proposal protocol esp
          - set security ipsec proposal ipsec-phase2-proposal authentication-algorithm hmac-md5-96
          - set security ipsec proposal ipsec-phase2-proposal encryption-algorithm aes-128-cbc 
          - set security ipsec proposal ipsec-phase2-proposal lifetime-seconds 1800
    - name: Set ipsec policy 
      junos_config:
        lines:
          - set security ipsec policy ipsec-phase2-policy perfect-forward-secrecy keys group2
          - set security ipsec policy ipsec-phase2-policy proposals ipsec-phase2-proposal
    - name: Set ipsec vpn interface and gateway  
      junos_config:
        lines:
          - set security ipsec vpn ike-vpn-vpnaas bind-interface st0.0
          - set security ipsec vpn ike-vpn-vpnaas ike gateway vpnaas
          - set security ipsec vpn ike-vpn-vpnaas ike ipsec-policy ipsec-phase2-policy
          - set security ipsec vpn ike-vpn-vpnaas establish-tunnels immediately
    - name: Bind vpn zone to tunnel interface  
      junos_config:
        lines:
          - set security zones security-zone vpn interfaces st0.0
    - name: Set up trust to vpn zone security policies
      junos_config:
        lines:
          - set security policies from-zone trust to-zone vpn policy 1 match source-address any
          - set security policies from-zone trust to-zone vpn policy 1 match destination-address any
          - set security policies from-zone trust to-zone vpn policy 1 match application any
          - set security policies from-zone trust to-zone vpn policy 1 then permit
    - name: Set up vpn to vpn trust security policies 
      junos_config:
        lines:
          - set security policies from-zone vpn to-zone trust policy 1 match source-address any
          - set security policies from-zone vpn to-zone trust policy 1 match destination-address any
          - set security policies from-zone vpn to-zone trust policy 1 match application any
          - set security policies from-zone vpn to-zone trust policy 1 then permit
    - name: Set up CUSTOMER-PRIVATE to vpn zone security policies 
      junos_config:
        lines:
          - set security policies from-zone CUSTOMER-PRIVATE to-zone vpn policy 2 description "Allow all traffic from CUSTOMER-PRIVATE to VPN zone"
          - set security policies from-zone CUSTOMER-PRIVATE to-zone vpn policy 2 match source-address VSI-PRI-NET    
          - set security policies from-zone CUSTOMER-PRIVATE to-zone vpn policy 2 match destination-address VPC-NETWORK
          - set security policies from-zone CUSTOMER-PRIVATE to-zone vpn policy 2 match application any
          - set security policies from-zone CUSTOMER-PRIVATE to-zone vpn policy 2 then permit
    - name: Set up vpn to CUSTOMER-PRIVATE zone security policies 
      junos_config:
        lines:
          - set security policies from-zone vpn to-zone CUSTOMER-PRIVATE policy 2 description "Allow all traffic from VPN zone to CUSTOMER PRIVATE zone "
          - set security policies from-zone vpn to-zone CUSTOMER-PRIVATE policy 2 match source-address VPC-NETWORK    
          - set security policies from-zone vpn to-zone CUSTOMER-PRIVATE policy 2 match destination-address VSI-PRI-NET
          - set security policies from-zone vpn to-zone CUSTOMER-PRIVATE policy 2 match application any
          - set security policies from-zone vpn to-zone CUSTOMER-PRIVATE policy 2 then permit
    - name: Add VPN ports to firewall
      junos_config:
        lines:
          - set firewall filter PROTECT-IN term VPCVPN from destination-address "{{ vsrx_public_ip }}"/32
          - set firewall filter PROTECT-IN term VPCVPN from destination-address "{{ vsrx_private_ip }}"/32
          - set firewall filter PROTECT-IN term VPCVPN from protocol udp
          - set firewall filter PROTECT-IN term VPCVPN from port 500
          - set firewall filter PROTECT-IN term VPCVPN from port 4500
          - set firewall filter PROTECT-IN term VPCVPN then accept
        backup: yes
        backup_options:
          dir_path: '../config_backups'
          filename: standalone-config-ipsec.backup
