---
- hosts: vsrxlab
  vars:
    ansible_command_timeout: 120
  gather_facts: no
  tasks:
    - name: Retrieve Junos OS version
      junipernetworks.junos.junos_command:
        commands: show interfaces
      when: ansible_network_os == 'junipernetworks.junos.junos'
      register: junos_interfaces
    - name: show interfaces 
      debug:        
        var: junos_interfaces